### ISSUE TITLE
Failure for large area and scale

### ISSUE THREAD

**Issue by NikosAlexandris** [dimartinot/gee_sar_fetcher#10]
The following example uses commit 4d01c19d1a9b6453b56e1e6e4badb0c362888e7c (i.e. without adding the `crs` parameter as described in #7 or other modifications).

Example of a somewhat large area and scale:
```
from geesarfetcher import fetch
import datetime
sentinel1_2019_06_descending = fetch(
    top_left = [5.26948161, 49.97440374],
    bottom_right = [8.07913236, 47.90621773],
    start_date = datetime.datetime(2019, 6, 1),
    end_date = datetime.datetime(2019, 6, 3),
    ascending=False,
    scale=1000,
)
```
fails raising the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-bd8e358c5d44> in <module>
      7     end_date = datetime.datetime(2019, 6, 3),
      8     ascending=False,
----> 9     scale=1000,
     10 )

/geoyeux/geo/projects/thermopolis/demonstration/code/gee_sar_fetcher/geesarfetcher/__init__.py in fetch(top_left, bottom_right, coords, start_date, end_date, ascending, scale, n_jobs)
    241     lats, lons = tuple(zip(*[(p["lat"], p["lon"]) for p in pixel_values]))
    242     lats = np.array(lats).reshape((height, width))
--> 243     lons = np.array(lons).reshape((height, width))
    244     coordinates = np.zeros((height, width,2))
    245     coordinates[:,:,0] = lats

ValueError: cannot reshape array of size 71834 into shape (362,198)
```

**Comment by dimartinot** [comment]
I will this investigate this shortly. Needless to say that this is not an expected behaviour. My take on this is is that the function [`define_image_shape(pixel_values)`](https://github.com/dimartinot/gee_sar_fetcher/blob/dev/geesarfetcher/utils/__init__.py#L128) provides wrongly evaluated width and height.

In your case, it finds 362 pixel width-wise, but this quantity does not divide 71834, hence resulting in a wrongly generated image. I will now be investigating on this behaviour and I will try to find a workaround ! 

Thanks for noticing it !

**Comment by NikosAlexandris** [comment]
I am also working on it. Whenever the number of `pixel_values` won't be _integer divisible_, the script will fail.

An idea... I think a design choice has to be made here. Either strictly build rectangular geometries (as in `ee.Geometry.Rectangle`?) or add one more row (height) or column (width) to locate all available pixel valuse in the image and (eventually) fill-in with No Data the remaining pixels (difference between `height * width` - `len(pixel_values)`).

Makes sense?

**Comment by dimartinot** [comment]
I came up to the same conclusion. On the specific case of the query you specified, I counted the occurence of each latitude et longitude values:
```
(array([47.91164568, 47.92062883, 47.92961198, 47.93859514, 47.94757829,
       47.95656144, 47.9655446 , 47.97452775, 47.9835109 , 47.99249405,
       48.00147721, 48.01046036, 48.01944351, 48.02842667, 48.03740982,
       48.04639297, 48.05537612, 48.06435928, 48.07334243, 48.08232558,
       48.09130874, 48.10029189, 48.10927504, 48.11825819, 48.12724135,
       48.1362245 , 48.14520765, 48.15419081, 48.16317396, 48.17215711,
       48.18114026, 48.19012342, 48.19910657, 48.20808972, 48.21707288,
       48.22605603, 48.23503918, 48.24402233, 48.25300549, 48.26198864,
       48.27097179, 48.27995495, 48.2889381 , 48.29792125, 48.3069044 ,
       48.31588756, 48.32487071, 48.33385386, 48.34283701, 48.35182017,
       48.36080332, 48.36978647, 48.37876963, 48.38775278, 48.39673593,
       48.40571908, 48.41470224, 48.42368539, 48.43266854, 48.4416517 ,
       48.45063485, 48.459618  , 48.46860115, 48.47758431, 48.48656746,
       48.49555061, 48.50453377, 48.51351692, 48.52250007, 48.53148322,
       48.54046638, 48.54944953, 48.55843268, 48.56741584, 48.57639899,
       48.58538214, 48.59436529, 48.60334845, 48.6123316 , 48.62131475,
       48.63029791, 48.63928106, 48.64826421, 48.65724736, 48.66623052,
       48.67521367, 48.68419682, 48.69317998, 48.70216313, 48.71114628,
       48.72012943, 48.72911259, 48.73809574, 48.74707889, 48.75606205,
       48.7650452 , 48.77402835, 48.7830115 , 48.79199466, 48.80097781,
       48.80996096, 48.81894412, 48.82792727, 48.83691042, 48.84589357,
       48.85487673, 48.86385988, 48.87284303, 48.88182619, 48.89080934,
       48.89979249, 48.90877564, 48.9177588 , 48.92674195, 48.9357251 ,
       48.94470826, 48.95369141, 48.96267456, 48.97165771, 48.98064087,
       48.98962402, 48.99860717, 49.00759033, 49.01657348, 49.02555663,
       49.03453978, 49.04352294, 49.05250609, 49.06148924, 49.0704724 ,
       49.07945555, 49.0884387 , 49.09742185, 49.10640501, 49.11538816,
       49.12437131, 49.13335446, 49.14233762, 49.15132077, 49.16030392,
       49.16928708, 49.17827023, 49.18725338, 49.19623653, 49.20521969,
       49.21420284, 49.22318599, 49.23216915, 49.2411523 , 49.25013545,
       49.2591186 , 49.26810176, 49.27708491, 49.28606806, 49.29505122,
       49.30403437, 49.31301752, 49.32200067, 49.33098383, 49.33996698,
       49.34895013, 49.35793329, 49.36691644, 49.37589959, 49.38488274,
       49.3938659 , 49.40284905, 49.4118322 , 49.42081536, 49.42979851,
       49.43878166, 49.44776481, 49.45674797, 49.46573112, 49.47471427,
       49.48369743, 49.49268058, 49.50166373, 49.51064688, 49.51963004,
       49.52861319, 49.53759634, 49.5465795 , 49.55556265, 49.5645458 ,
       49.57352895, 49.58251211, 49.59149526, 49.60047841, 49.60946157,
       49.61844472, 49.62742787, 49.63641102, 49.64539418, 49.65437733,
       49.66336048, 49.67234364, 49.68132679, 49.69030994, 49.69929309,
       49.70827625, 49.7172594 , 49.72624255, 49.73522571, 49.74420886,
       49.75319201, 49.76217516, 49.77115832, 49.78014147, 49.78912462,
       49.79810778, 49.80709093, 49.81607408, 49.82505723, 49.83404039,
       49.84302354, 49.85200669, 49.86098985, 49.869973  , 49.87895615,
       49.8879393 , 49.89692246, 49.90590561, 49.91488876, 49.92387191,
       49.93285507, 49.94183822, 49.95082137, 49.95980453, 49.96878768,
       49.97777083]), array([198, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312, 312,
       312, 312, 312, 312, 312, 312, 312, 312, 312, 188], dtype=int64))
```

You can indeed notice that the appearance of every latitude value is not constant as pre-supposed by my code. This indeed means that some (lat, lon) coordinates within the queried regions are missing. We could keep the idea of creating a rectangular region and fill-in missing values with `np.nan`. It would be the easiest solution and it leaves to the user the choice wether they discard incomplete columns/rows.

The size of the rectangular region would then be the max occurence count amongst latitudes times the maximum occurrence count amongst longitudes

**Comment by NikosAlexandris** [comment]
> I am also working on it. Whenever the number of `pixel_values` won't be _integer divisible_, the script will fail.
> 
> An idea... I think a design choice has to be made here. Either strictly build rectangular geometries (as in `ee.Geometry.Rectangle`?) or add one more row (height) or column (width) to locate all available pixel valuse in the image and (eventually) fill-in with No Data the remaining pixels (difference between `height * width` - `len(pixel_values)`).
> 
> Makes sense?

Some brainstorming pseudo-code:
```
if len(unique(latitude)) > len(unique(longitude)):
    final_height = height + 1
else:
    final_width = width + 1
```

**Comment by NikosAlexandris** [comment]
> ..
> We could keep the idea of creating a rectangular region and fill-in missing values with `np.nan`. It would be the easiest solution and it leaves to the user the choice wether they discard incomplete columns/rows.
> 
> The size of the rectangular region would then be the max occurence count amongst latitudes times the maximum occurrence count amongst longitudes

Probably this is a rational compromise. It would not be _nice_ to reject useful data. I am sure there must be an elegant way to fill-in missing cells. I don't know if `numpy.resize()` (or `ndarray.resize()` for the matter) can be useful too.  Also, there is this "strange" 
> _Even with reshape(), if you want to add a dimension to the beginning or end, you do not have to explicitly specify the size by expanding the original shape with *._

(from https://note.nkmk.me/en/python-numpy-newaxis/)

**Comment by dimartinot** [comment]
I redesigned the image generation process to take into account cases where not every coordinate of the selected region is listed in the `per_coord_dict` variable. It comes with the drawback of a bit longer computation time for image generation (around +3min in worst case scenario). The potential to parallelise the proces was studied but nothing operational is found at the moment.

**Comment by NikosAlexandris** [comment]
Cool stuff. My example area works.
