### ISSUE TITLE
Compress further main body of code

### ISSUE THREAD

**Issue by NikosAlexandris** [dimartinot/gee_sar_fetcher#9]
Please consider to move helper functions (like) https://github.com/dimartinot/gee_sar_fetcher/blob/4d01c19d1a9b6453b56e1e6e4badb0c362888e7c/geesarfetcher/__init__.py#L130-L145 and https://github.com/dimartinot/gee_sar_fetcher/blob/4d01c19d1a9b6453b56e1e6e4badb0c362888e7c/geesarfetcher/__init__.py#L208-L220 out of the _main_ program.

Ideally, the _main_ program (API?) should be minimal and read easily as in what it does and not necessarily how.

**Comment by NikosAlexandris** [comment]
An example of what I imagine in my experimental fork: https://github.com/NikosAlexandris/gee_sar_fetcher/blob/e757fa2a596738bfba30e661defc365a731b742b/geesarfetcher/api.py

**Comment by NikosAlexandris** [comment]
See also https://github.com/NikosAlexandris/gee_sar_fetcher/blob/6f493600194474790c3d4c61698d18560e3ff340/geesarfetcher/api.py

**Comment by dimartinot** [comment]
Hey @NikosAlexandris , I just pushed a fix to your recommandation. Many thanks as it was very wise from you to advise it. I have additional potentials for code factorisation within the new api module but I believe that the current state of the code was good enough for a new release. :)
